edition = "2018"
# fn_single_line = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# ignore = []
# match_block_trailing_comma = true
max_width = 100
# merge_imports = true
newline_style = "Unix"
# overflow_delimited_expr = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
# width_heuristics = "Max"
# wrap_comments = true
